import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import { BookOpen, SpellCheck, ShieldAlert, Sparkles } from 'lucide-react';

const toolsData = [
    {
        title: "Citation Generator",
        description: "Instantly generate accurate academic citations in APA 7th, MLA 9th, Harvard, Chicago, IEEE, and Vancouver formatting. Supports books, journals, websites, and dynamically builds your downloadable bibliography list.",
        icon: BookOpen,
        slug: "citation-generator",
    },
    {
        title: "Grammar & Spell Checker",
        description: "Submit your essays, articles, or reports to scan for grammatical errors, spelling slips, and stylistic improvements. Renders instant explanations and one-click corrections to polish your writing.",
        icon: SpellCheck,
        slug: "grammar-checker",
    },
    {
        title: "Linguistic AI Detector",
        description: "Identify AI footprints, uniform sentence structures, and predictable text patterns. Checks sentence-level perplexity and highlights paragraphs likely generated by ChatGPT, Claude, or other LLMs.",
        icon: ShieldAlert,
        slug: "ai-detector",
    },
    {
        title: "AI Text Humanizer",
        description: "Humanize your AI-generated text to alter robotic syntax, improve structural variation, and bypass AI pattern detection while retaining the original context of your writing.",
        icon: Sparkles,
        slug: "ai-humanizer",
    }
];

const Tools = () => {
    return (
        <div className="page-tools">
            <Helmet>
                <title>Free Academic Writing Tools | Academic Wizard</title>
                <meta name="description" content="Use our free suite of academic tools: Citation Generator (APA/MLA/Harvard), Grammar Checker, AI Detector, and Streamlit AI Humanizer." />
                <link rel="canonical" href="https://academicwizard.online/tools" />
                <meta property="og:title" content="Free Academic Writing Tools | Academic Wizard" />
                <meta property="og:description" content="Enhance your essays and research papers with our Citation Generator, Grammar Checker, AI Detector, and AI Humanizer." />
                <meta property="og:url" content="https://academicwizard.online/tools" />
            </Helmet>

            <PageHeader 
                title="Free Student Tools" 
                subtitle="High-utility, client-side academic tools designed to elevate your research, writing, and formatting."
                breadcrumbs={[
                    { name: 'Home', url: '/' },
                    { name: 'Tools', url: '/tools' }
                ]}
            />

            <section className="py-20 bg-bg-primary text-white">
                <div className="container space-y-20">
                    {toolsData.map((tool, index) => (
                        <div
                            key={index}
                            className={`flex flex-col lg:flex-row gap-12 items-center ${index % 2 === 1 ? 'lg:flex-row-reverse' : ''}`}
                        >
                            <div className="w-full lg:w-1/3">
                                <Link to={`/tools/${tool.slug}`} className="block group">
                                    <div 
                                        className="glass-card p-12 flex items-center justify-center aspect-square border-accent-gold/20 group-hover:border-accent-gold/50 transition-colors duration-500 rounded-2xl" 
                                        style={{ borderColor: 'rgba(212, 175, 55, 0.2)' }}
                                    >
                                        <tool.icon 
                                            size={100} 
                                            className="text-accent-gold group-hover:scale-110 transition-transform duration-500" 
                                            style={{ color: 'var(--accent-gold)' }} 
                                        />
                                    </div>
                                </Link>
                            </div>
                            <div className="w-full lg:w-2/3">
                                <Link to={`/tools/${tool.slug}`}>
                                    <h2 className="text-3xl font-bold mb-6 font-heading text-white hover:text-accent-gold transition-colors duration-300">
                                        {tool.title}
                                    </h2>
                                </Link>
                                <p className="text-text-secondary text-lg leading-relaxed mb-8" style={{ color: 'var(--text-secondary)' }}>
                                    {tool.description}
                                </p>
                                <div className="flex gap-4">
                                    <Link to={`/tools/${tool.slug}`}>
                                        <Button>
                                            Launch Tool
                                        </Button>
                                    </Link>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    );
};

export default Tools;
