import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import Button from '../components/Button';
import { BookOpen, SpellCheck, ShieldAlert, Sparkles } from 'lucide-react';

const toolsData = [
    {
        title: "Citation Generator",
        description: "Instantly generate accurate academic citations in APA 7th, MLA 9th, Harvard, Chicago, IEEE, and Vancouver formatting. Supports books, journals, websites, and dynamically builds your downloadable bibliography list.",
        icon: BookOpen,
        slug: "citation-generator",
    },
    {
        title: "Grammar & Spell Checker",
        description: "Submit your essays, articles, or reports to scan for grammatical errors, spelling slips, and stylistic improvements. Renders instant explanations and one-click corrections to polish your writing.",
        icon: SpellCheck,
        slug: "grammar-checker",
    },
    {
        title: "Linguistic AI Detector",
        description: "Identify AI footprints, uniform sentence structures, and predictable text patterns. Checks sentence-level perplexity and highlights paragraphs likely generated by ChatGPT, Claude, or other LLMs.",
        icon: ShieldAlert,
        slug: "ai-detector",
    },
    {
        title: "AI Text Humanizer",
        description: "Humanize your AI-generated text to alter robotic syntax, improve structural variation, and bypass AI pattern detection while retaining the original context of your writing.",
        icon: Sparkles,
        slug: "ai-humanizer",
    }
];

const Tools = () => {
    return (
        <div className="page-tools">
            <Helmet>
                <title>Free Academic Writing Tools | Academic Wizard</title>
                <meta name="description" content="Boost your grades with our free academic tools: Automatic Citation Generator, Online Grammar Editor, Essay AI Detector, and Streamlit Text Humanizer." />
                <link rel="canonical" href="https://academicwizard.online/tools" />
                <meta property="og:title" content="Free Academic Writing Tools | Academic Wizard" />
                <meta property="og:description" content="Automate bibliography generation, fix grammar mistakes, and scan/humanize AI text with our free tools suite." />
                <meta property="og:url" content="https://academicwizard.online/tools" />
                <script type="application/ld+json">
                    {JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "CollectionPage",
                        "name": "Free Academic Writing Tools Suite",
                        "url": "https://academicwizard.online/tools",
                        "description": "Unlock Academic Wizard's free suite of college tools, including Citation Generator, Grammar and Spell Checker, AI Content Detector, and AI Text Humanizer.",
                        "hasPart": [
                            {
                                "@type": "WebApplication",
                                "name": "Citation Generator",
                                "url": "https://academicwizard.online/tools/citation-generator",
                                "applicationCategory": "EducationalApplication",
                                "operatingSystem": "All",
                                "browserRequirements": "Requires HTML5"
                            },
                            {
                                "@type": "WebApplication",
                                "name": "Grammar & Spell Checker",
                                "url": "https://academicwizard.online/tools/grammar-checker",
                                "applicationCategory": "EducationalApplication",
                                "operatingSystem": "All",
                                "browserRequirements": "Requires HTML5"
                            },
                            {
                                "@type": "WebApplication",
                                "name": "Linguistic AI Detector",
                                "url": "https://academicwizard.online/tools/ai-detector",
                                "applicationCategory": "EducationalApplication",
                                "operatingSystem": "All",
                                "browserRequirements": "Requires HTML5"
                            },
                            {
                                "@type": "WebApplication",
                                "name": "AI Text Humanizer",
                                "url": "https://academicwizard.online/tools/ai-humanizer",
                                "applicationCategory": "EducationalApplication",
                                "operatingSystem": "All",
                                "browserRequirements": "Requires HTML5"
                            }
                        ]
                    })}
                </script>
            </Helmet>

            <PageHeader 
                title="Free Student Tools" 
                subtitle="High-utility, client-side academic tools designed to elevate your research, writing, and formatting."
                breadcrumbs={[
                    { name: 'Home', url: '/' },
                    { name: 'Tools', url: '/tools' }
                ]}
            />

            <section className="py-20 text-white">
                <div className="container space-y-20">
                    {toolsData.map((tool, index) => (
                        <div
                            key={index}
                            className={`flex flex-col lg:flex-row gap-12 items-center ${index % 2 === 1 ? 'lg:flex-row-reverse' : ''}`}
                        >
                            <div className="w-full lg:w-1/3">
                                <Link to={`/tools/${tool.slug}`} className="block group">
                                    <div 
                                        className="glass-card p-12 flex items-center justify-center aspect-square border-accent-gold/20 group-hover:border-accent-gold/50 transition-colors duration-500 rounded-2xl" 
                                        style={{ borderColor: 'rgba(212, 175, 55, 0.2)' }}
                                    >
                                        <tool.icon 
                                            size={100} 
                                            className="text-accent-gold group-hover:scale-110 transition-transform duration-500" 
                                            style={{ color: 'var(--accent-gold)' }} 
                                        />
                                    </div>
                                </Link>
                            </div>
                            <div className="w-full lg:w-2/3">
                                <Link to={`/tools/${tool.slug}`}>
                                    <h2 className="text-3xl font-bold mb-6 font-heading text-white hover:text-accent-gold transition-colors duration-300">
                                        {tool.title}
                                    </h2>
                                </Link>
                                <p className="text-text-secondary text-lg leading-relaxed mb-8" style={{ color: 'var(--text-secondary)' }}>
                                    {tool.description}
                                </p>
                                <div className="flex gap-4">
                                    <Link to={`/tools/${tool.slug}`}>
                                        <Button>
                                            Launch Tool
                                        </Button>
                                    </Link>
                                </div>
                            </div>
                        </div>
                    ))}

                    {/* Detailed Content & FAQ Section (GEO/AEO optimized) */}
                    <div className="border-t border-white/10 pt-20 max-w-4xl mx-auto space-y-12">
                        <div className="space-y-4">
                            <h3 className="text-2xl font-bold font-heading text-accent-gold" style={{ color: 'var(--accent-gold)' }}>
                                Elevate Your Research with Free Academic Writing Tools
                            </h3>
                            <p className="text-text-secondary leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                                Academic writing requires precision, proper formatting, and rigorous integrity. To support students in their university assignments, essays, and PhD research, Academic Wizard offers this suite of tools. Our citation builder, grammar checker, and AI detection tools operate entirely within the browser, ensuring your work is uploaded nowhere, keeping your research 100% private and secure.
                            </p>
                        </div>

                        {/* Visual FAQ Block */}
                        <div className="space-y-6">
                            <h3 className="text-xl font-bold font-heading text-white">Frequently Asked Questions</h3>
                            
                            <div className="space-y-4">
                                <div className="bg-white/5 border border-white/5 p-6 rounded-xl space-y-2">
                                    <h4 className="font-bold text-white text-sm">Are these academic writing tools completely free?</h4>
                                    <p className="text-text-secondary text-xs leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                                        Yes, our entire suite of academic tools is completely free. We provide a limited daily trial for visitors, which can be unlocked for unlimited weekly use by requesting a free activation code from our support team on WhatsApp or social media.
                                    </p>
                                </div>
                                <div className="bg-white/5 border border-white/5 p-6 rounded-xl space-y-2">
                                    <h4 className="font-bold text-white text-sm">Do these tools store my essays or private data?</h4>
                                    <p className="text-text-secondary text-xs leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                                        No. Unlike commercial alternatives that save your work to database servers, Academic Wizard's tools analyze data locally on your computer. Your text is never stored, sold, or shared with third parties, keeping your intellectual property safe.
                                    </p>
                                </div>
                                <div className="bg-white/5 border border-white/5 p-6 rounded-xl space-y-2">
                                    <h4 className="font-bold text-white text-sm">Which academic citation formats are supported?</h4>
                                    <p className="text-text-secondary text-xs leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                                        Our Citation Generator supports major styling guidelines, including APA 7th Edition, MLA 9th Edition, Harvard, Chicago manual of style, IEEE, and Vancouver numeric formatting, suitable for all college subjects.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
};

export default Tools;
